<?php
/**
 * This class controls the public-facing functionality of the plugin.
 *
 * This class contains the code necessary to display a custom category
 * page to the users of a site, by overriding the default theme template 
 * with one generated by the plugin.
 *
 * @link       https://aileenhuang.dev
 * @since      1.0.0
 * 
 * @package    Ak_Category_Toc
 * @subpackage Ak_Category_Toc/public
 * @author     axkeyz <aileen.huang@outlook.co.nz>
 */

class Ak_Category_Toc_Public {

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param string    $plugin_name	The name of the plugin
	 * @param string    $version	The version of this plugin
	 */
	public function __construct( $plugin_name, $version ) {

		$this->plugin_name = $plugin_name;
		$this->version = $version;

	}

	/**
	 * Register the stylesheets for the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Ak_Category_Toc_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Ak_Category_Toc_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'css/ak-category-toc-public.css', array(), $this->version, 'all' );

	}

	/**
	 * Register the JavaScript for the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Ak_Category_Toc_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Ak_Category_Toc_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_script( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'js/ak-category-toc-public.js', array( 'jquery' ), $this->version, false );

	}

	/**
	 * The function overrides the current theme's category template with a
	 * template generated by this plugin.
	 *
	 * @since    1.0.0
	 * @author	 axkeyz
	 * 
	 * @param string	$template	Lookup template file path
	 */
	public function ak_override_category_template($template){
        // Get all categories
        $ak_all_categories = get_categories();

        foreach ($ak_all_categories as $ak_single_category) {
            if ( is_category($ak_single_category) ) {
				// Override with current template is a category
				$template = AK_PLUGIN_DIR . 'public/partials/ak-category-toc-public-display.php';
                break;
            }
        }
        return $template;
    }
}
